/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeCallee,
  IPancakeCalleeInterface,
} from "../IPancakeCallee";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "pancakeCall",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPancakeCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeCalleeInterface {
    return new Interface(_abi) as IPancakeCalleeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeCallee {
    return new Contract(address, _abi, runner) as unknown as IPancakeCallee;
  }
}
