/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BEP20 } from "./BEP20";
export type { IBEP20 } from "./IBEP20";
export type { Ownable } from "./Ownable";
export type { SobaToken } from "./SobaToken";
