/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BEP20__factory>;
    getContractFactory(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBEP20__factory>;
    getContractFactory(
      name: "IMigratorChef",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMigratorChef__factory>;
    getContractFactory(
      name: "MasterChef",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MasterChef__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SobaToken__factory>;
    getContractFactory(
      name: "SyrupBar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SyrupBar__factory>;
    getContractFactory(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BEP20__factory>;
    getContractFactory(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBEP20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SobaToken__factory>;
    getContractFactory(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BEP20__factory>;
    getContractFactory(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBEP20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SobaToken__factory>;
    getContractFactory(
      name: "SyrupBar",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SyrupBar__factory>;

    getContractAt(
      name: "BEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BEP20>;
    getContractAt(
      name: "IBEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBEP20>;
    getContractAt(
      name: "IMigratorChef",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMigratorChef>;
    getContractAt(
      name: "MasterChef",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MasterChef>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SobaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SobaToken>;
    getContractAt(
      name: "SyrupBar",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SyrupBar>;
    getContractAt(
      name: "BEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BEP20>;
    getContractAt(
      name: "IBEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBEP20>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SobaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SobaToken>;
    getContractAt(
      name: "BEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BEP20>;
    getContractAt(
      name: "IBEP20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBEP20>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SobaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SobaToken>;
    getContractAt(
      name: "SyrupBar",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SyrupBar>;

    deployContract(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "IMigratorChef",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMigratorChef>;
    deployContract(
      name: "MasterChef",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MasterChef>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "SyrupBar",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SyrupBar>;
    deployContract(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "BEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "SyrupBar",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SyrupBar>;

    deployContract(
      name: "BEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "IMigratorChef",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMigratorChef>;
    deployContract(
      name: "MasterChef",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MasterChef>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "SyrupBar",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SyrupBar>;
    deployContract(
      name: "BEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "BEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BEP20>;
    deployContract(
      name: "IBEP20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBEP20>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SobaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SobaToken>;
    deployContract(
      name: "SyrupBar",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SyrupBar>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
