/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as masterChefSol from "./MasterChef.sol";
export type { masterChefSol };
import type * as sobaTokenSol from "./SobaToken.sol";
export type { sobaTokenSol };
import type * as syrupBarSol from "./SyrupBar.sol";
export type { syrupBarSol };
export * as factories from "./factories";
export type { BEP20 } from "./MasterChef.sol/BEP20";
export { BEP20__factory } from "./factories/MasterChef.sol/BEP20__factory";
export type { IBEP20 } from "./MasterChef.sol/IBEP20";
export { IBEP20__factory } from "./factories/MasterChef.sol/IBEP20__factory";
export type { IMigratorChef } from "./MasterChef.sol/IMigratorChef";
export { IMigratorChef__factory } from "./factories/MasterChef.sol/IMigratorChef__factory";
export type { MasterChef } from "./MasterChef.sol/MasterChef";
export { MasterChef__factory } from "./factories/MasterChef.sol/MasterChef__factory";
export type { Ownable } from "./MasterChef.sol/Ownable";
export { Ownable__factory } from "./factories/MasterChef.sol/Ownable__factory";
export type { SobaToken } from "./MasterChef.sol/SobaToken";
export { SobaToken__factory } from "./factories/MasterChef.sol/SobaToken__factory";
export type { SyrupBar } from "./MasterChef.sol/SyrupBar";
export { SyrupBar__factory } from "./factories/MasterChef.sol/SyrupBar__factory";
